# Generated by Django 5.2.17 on 2026-10-02 02:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2555)),
                ('category', models.CharField(choices=[('TOP', 'Atasan / Tops'), ('BOTTOM', 'Bawahan / Bottoms'), ('OUTER', 'Pakaian Luar / Outerwear'), ('DRESS', 'Gaun / Dress'), ('SHOES', 'Sepatu / Shoes'), ('ACCESSORY', 'Aksesoris / Accessories')], max_length=20)),
                ('material', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('wear_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
