# Generated by Django 5.2.17 on 2026-10-02 10:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_name', models.CharField(max_length=150, verbose_name='Nama pakaian')),
                ('category', models.CharField(choices=[('top', 'Atasan'), ('bottom', 'Bawahan'), ('outer', 'Jaket / outerwear'), ('dress', 'Dress / pakaian terusan'), ('other', 'Lainnya')], max_length=20, verbose_name='Kategori')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Merek')),
                ('product_url', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Link pembelian')),
                ('existing_clothing', models.CharField(choices=[('usable', 'Ada dan masih layak'), ('repairable', 'Ada tetapi perlu diperbaiki'), ('none', 'Belum ada')], max_length=20, verbose_name='Pakaian yang sudah dimiliki')),
                ('purpose', models.CharField(choices=[('routine', 'Kebutuhan rutin'), ('replacement', 'Mengganti pakaian yang tidak layak'), ('occasion', 'Acara tertentu'), ('variety', 'Menambah variasi koleksi')], max_length=20, verbose_name='Tujuan penggunaan')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Harga pakaian (Rp)')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Budget pembelian (Rp)')),
                ('expected_wears', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Perkiraan total pemakaian')),
                ('target_cpw', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Target biaya per pakai (Rp)')),
                ('wears_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Pemakaian per bulan')),
                ('decision', models.CharField(choices=[('undecided', 'Belum diputuskan'), ('use_existing', 'Pakai pakaian yang ada'), ('repair', 'Perbaiki pakaian yang ada'), ('borrow_rent', 'Pinjam atau sewa'), ('alternative', 'Cari alternatif'), ('postpone', 'Tunda pembelian'), ('buy', 'Beli dengan rencana pemakaian')], default='undecided', max_length=20, verbose_name='Keputusan')),
                ('decision_note', models.TextField(blank=True, max_length=1000, verbose_name='Catatan keputusan')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('carbon_kg_co2e', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('carbon_reference', models.CharField(blank=True, max_length=200)),
                ('carbon_source', models.CharField(blank=True, max_length=200)),
                ('carbon_scope', models.CharField(blank=True, max_length=500)),
                ('carbon_estimated_at', models.DateTimeField(blank=True, null=True)),
                ('rule_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
